"""Create Sessions

Revision ID: 27f63e48c6c4
Revises: d4e3b890e3d7
Create Date: 2021-01-09 11:57:18.916146

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '27f63e48c6c4'
down_revision = 'd4e3b890e3d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'session',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column(
            'created',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'choice_for_session',
        sa.Column('choice_id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['choice_id'], ['choice_history.id']),
        sa.ForeignKeyConstraint(['session_id'], ['session.id']),
        sa.PrimaryKeyConstraint('choice_id', 'session_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choice_for_session')
    op.drop_table('session')
    # ### end Alembic commands ###
