"""Create archive table

Revision ID: 84d522610b47
Revises:
Create Date: 2020-07-09 15:54:08.022673

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '84d522610b47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'archive',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('content', sa.LargeBinary(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column(
            'created',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive')
    # ### end Alembic commands ###
