"""Create choice history table

Revision ID: d4e3b890e3d7
Revises: eda5c539028e
Create Date: 2020-07-09 18:07:04.107503

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd4e3b890e3d7'
down_revision = 'eda5c539028e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'choice_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('archive_id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column(
            'created',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['archive_id'], ['archive.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choice_history')
    # ### end Alembic commands ###
